export const menuData = {
    "categories": [
        {
            "name": "Pizza",
            "items": [
                { "name": "Italian", "description": "Sauce, Cheese, Ham, Salami, Fresh Mushroom & Olives", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Sauce", "Cheese", "Ham", "Salami", "Fresh Mushroom", "Olives"] },
                { "name": "Margherita", "description": "Garlic, Oregano, Mozzarella Cheese, Fresh Tomato On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Garlic", "Oregano", "Mozzarella Cheese", "Fresh Tomato", "Tomato Base"] },
                { "name": "Cheesy Pepperoni", "description": "Garlic, Oregano, Mozzarella Cheese, Double Pepperoni On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Garlic", "Oregano", "Mozzarella Cheese", "Double Pepperoni", "Tomato Base"] },
                { "name": "Aussie Bob", "description": "Mozzarella Cheese, Bacon, Fresh Tomato On A BBQ Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Bacon", "Fresh Tomato", "BBQ Sauce Base"] },
                { "name": "Australian", "description": "Double Mozzarella Cheese, Ham On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Double Mozzarella Cheese", "Ham", "Tomato Base"] },
                { "name": "Vegetarian", "description": "Mozzarella Cheese, Onion, Capsicum, Fresh Mushroom, Pineapple, Olives On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Onion", "Capsicum", "Fresh Mushroom", "Pineapple", "Olives", "Tomato Base"] },
                { "name": "Double Burger Bite", "description": "Mozzarella Cheese, Bacon, Ground Beef Topped With A Swirl Of Aioli On A BBQ Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Bacon", "Ground Beef", "Aioli", "BBQ Sauce Base"] },
                { "name": "Meatlovers", "description": "Mozzarella Cheese, Ham, Pepperoni, Bacon, Salami On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Ham", "Pepperoni", "Bacon", "Salami", "Tomato Base"] },
                { "name": "Mexican", "description": "Mozzarella Cheese, Ham, Pepperoni, Capsicum, Jalapeno Peppers On A Tomato Base.", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Ham", "Pepperoni", "Capsicum", "Jalapeno Peppers", "Tomato Base"] },
                { "name": "Special", "description": "Mozzarella Cheese, Ham, Salami, Capsicum, Fresh Mushroom, Kalamata, Olives, Anchovies On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Ham", "Salami", "Capsicum", "Fresh Mushroom", "Kalamata", "Olives", "Anchovies", "Tomato Base"] },
                { "name": "Deluxe", "description": "Mozzarella Cheese, Onion, Capsicum, Fresh Mushroom, Pineapple, Bacon On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Onion", "Capsicum", "Fresh Mushroom", "Pineapple", "Bacon", "Tomato Base"] },
                { "name": "Ham & Salami", "description": "Mozzarella Cheese, Ham, Salami On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Ham", "Salami", "Tomato Base"] },
                { "name": "Ham & Pineapple", "description": "Mozzarella Cheese, Ham, Pineapple On a Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Ham", "Pineapple", "Tomato Base"] },
                { "name": "Ham & Bacon", "description": "Mozzarella Cheese, Ham, Bacon On a Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Ham", "Bacon", "Tomato Base"] },
                { "name": "Ham & Mushroom", "description": "Mozzarella Cheese, Ham, Fresh Mushroom On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Ham", "Fresh Mushroom", "Tomato Base"] },
                { "name": "Cheese Pizza", "description": "Mozzarella Cheese, On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Tomato Base"] },
                { "name": "Garlic Butter & Cheese", "description": "Mozzarella Cheese, On A Garlic Butter Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 14.50, "Large": 19.50, "Family": 26.50, "Party": 32.50 }, "ingredients": ["Mozzarella Cheese", "Garlic Butter Base"] },
                { "name": "The Neapolitan", "description": "Garlic, Oregano, Mozzarella Cheese, Fresh Basil, Bocochinni Cheese, Fresh Tomato On A Tomato Base.", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 15.80, "Large": 20.50, "Family": 27.30, "Party": 35.40 }, "ingredients": ["Garlic", "Oregano", "Mozzarella Cheese", "Fresh Basil", "Bocochinni Cheese", "Fresh Tomato", "Tomato Base"] },
                { "name": "The Cheese Burger", "description": "Bbq sauce base mozzarella cheese, onions, fresh tomato, homemade beef, pickles, topped with a swirl of tomato sauce & mustard", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["BBQ Sauce Base", "Mozzarella Cheese", "Onions", "Fresh Tomato", "Homemade Beef", "Pickles", "Tomato Sauce", "Mustard"] },
                { "name": "Quattro Formaggi", "description": "(4 Cheeses) Mozzarella Cheese, Bocconcini Cheese, Feta Cheese Topped With Shaved Parmesan Cheese, Garlic, Oregano On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["Mozzarella Cheese", "Bocconcini Cheese", "Feta Cheese", "Shaved Parmesan Cheese", "Garlic", "Oregano", "Tomato Base"] },
                { "name": "Mega Margherita", "description": "Mozzarella Cheese, Bocconcini Cheese, Fire Roasted Peppers, Fresh Tomato, Kalamata Olives, Garlic, Oregano On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["Mozzarella Cheese", "Bocconcini Cheese", "Fire Roasted Peppers", "Fresh Tomato", "Kalamata Olives", "Garlic", "Oregano", "Tomato Base"] },
                { "name": "BBQ Roast Chicken", "description": "Mozzarella Cheese, Onion, Capsicum, Bacon, Roasted Chicken On BBQ Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["Mozzarella Cheese", "Onion", "Capsicum", "Bacon", "Roasted Chicken", "BBQ Sauce Base"] },
                { "name": "Chicken & Pineapple", "description": "Mozzarella Cheese, Pineapple, Roasted Chicken On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["Mozzarella Cheese", "Pineapple", "Roasted Chicken", "Tomato Base"] },
                { "name": "Supreme", "description": "Mozzarella Cheese, Ham, Salami, Onion, Capsicum, Fresh Mushroom, Pineapple, Kalamata, Olives On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["Mozzarella Cheese", "Ham", "Salami", "Onion", "Capsicum", "Fresh Mushroom", "Pineapple", "Kalamata Olives", "Tomato Base"] },
                { "name": "Boss", "description": "Mozzarella Cheese, Pepperoni, Onion, Capsicum, Fresh Mushroom, Pineapple, Ground Beef, Bacon On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["Mozzarella Cheese", "Pepperoni", "Onion", "Capsicum", "Fresh Mushroom", "Pineapple", "Ground Beef", "Bacon", "Tomato Base"] },
                { "name": "Chef's Special", "description": "Double Mozzarella Cheese, Pepperoni, Fresh Mushroom, Kalamata Olives, Diced Bacon, Pineapple On A Spicy Tomato Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["Double Mozzarella Cheese", "Pepperoni", "Fresh Mushroom", "Kalamata Olives", "Diced Bacon", "Pineapple", "Spicy Tomato Sauce Base"] },
                { "name": "Bacon Deluxe", "description": "Mozzarella Cheese, Bacon, Ground Beef, Fresh Tomato, Topped With Aioli On A Bbq Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["Mozzarella Cheese", "Bacon", "Ground Beef", "Fresh Tomato", "Aioli", "BBQ Sauce Base"] },
                { "name": "Peppers Special", "description": "Mozzarella, Baby Spinach, Thinly sliced Prosciutto, Oven Roasted Chicken, Pumpkin, Fire Roasted Pepper, Jalapeno, Smoked bacon Rashers, Topped With Fresh Rocket & Shaved Parmesan On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella", "Baby Spinach", "Prosciutto", "Oven Roasted Chicken", "Pumpkin", "Fire Roasted Pepper", "Jalapeno", "Smoked Bacon Rashers", "Fresh Rocket", "Shaved Parmesan", "Tomato Base"] },
                { "name": "Bellisimo Meats", "description": "Mozzarella Cheese, Pepperoni, Ground Beef, Smoked Bacon Rashers Topped With Oven Roasted Chicken On A BBQ Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Pepperoni", "Ground Beef", "Smoked Bacon Rashers", "Oven Roasted Chicken", "BBQ Sauce Base"] },
                { "name": "Seven Mega Meats", "description": "Mozzarella Cheese, Virginian Ham, Ground Beef, Smoked Bacon Rashers, Oven Roasted Chicken, Hot pepperoni, Chorizo Sausage Topped With Marinated Lamb Yiros On A BBQ Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Virginian Ham", "Ground Beef", "Smoked Bacon Rashers", "Oven Roasted Chicken", "Hot Pepperoni", "Chorizo Sausage", "Marinated Lamb Yiros", "BBQ Sauce Base"] },
                { "name": "Lamb Yiros Pizza", "description": "Mozzarella Cheese, Onion, Fresh Tomato, Marinated Lamb Yiros, Topped With Our Awesome Homemade Garlic Sauce On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Onion", "Fresh Tomato", "Marinated Lamb Yiros", "Homemade Garlic Sauce", "Tomato Base"] },
                { "name": "Chicken Yiros Pizza", "description": "Mozzarella Cheese, Onion, Fresh Tomato, Marinated Chicken Yiros, Topped With Our Awesome Homemade Garlic Sauce On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Onion", "Fresh Tomato", "Marinated Chicken Yiros", "Homemade Garlic Sauce", "Tomato Base"] },
                { "name": "Combination Yiros Pizza", "description": "Mozzarella Cheese, Onion, Fresh Tomato, Marinated Lamb & Chicken Yiros, Topped With Our Awesome Homemade Garlic Sauce On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Onion", "Fresh Tomato", "Marinated Lamb Yiros", "Marinated Chicken Yiros", "Homemade Garlic Sauce", "Tomato Base"] },
                { "name": "Mediterranean", "description": "Garlic, Oregano, Mozzarella Cheese, Baby Spinach, Onion, Marinated Lamb, Oven Roasted Pumpkin topped with Mint Yoghurt & A Sprinkle Of Rosemary On A Spicy Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Garlic", "Oregano", "Mozzarella Cheese", "Baby Spinach", "Onion", "Marinated Lamb", "Oven Roasted Pumpkin", "Mint Yoghurt", "Rosemary", "Spicy Tomato Base"] },
                { "name": "Satay Chicken", "description": "Mozzarella Cheese, Onion, Fire Roosted Peppers, Fresh Mushrooms, Topped With Tender Juicy Chicken On A Spicy Satay Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Onion", "Fire Roosted Peppers", "Fresh Mushrooms", "Tender Juicy Chicken", "Spicy Satay Sauce Base"] },
                { "name": "Chicken Hawaiian", "description": "Mozzarella Cheese, Smoked Bacon Rashers, Pineapple, Virginian Ham, Roasted Chicken On A BBQ Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Smoked Bacon Rashers", "Pineapple", "Virginian Ham", "Roasted Chicken", "BBQ Sauce Base"] },
                { "name": "Reef & Beef", "description": "Mozzarella Cheese, Onion, Smoked Bacon Rashers, Ground Beef Topped With Marinated Lemon Pepper King Size Prawns Garnished with Lemon On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Onion", "Smoked Bacon Rashers", "Ground Beef", "Marinated Lemon Pepper King Size Prawns", "Lemon", "Tomato Base"] },
                { "name": "The Rocket", "description": "Mozzarella & Bocconcini Cheese, Garlic, Prosciuitto, Kalamata Olives, Fresh Tomato, Topped With Fresh Rocket & Shaved Parmesan Cheese On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Bocconcini Cheese", "Garlic", "Prosciuitto", "Kalamata Olives", "Fresh Tomato", "Fresh Rocket", "Shaved Parmesan Cheese", "Tomato Base"] },
                { "name": "The Don", "description": "Mozzarella Cheese, Garlic, Sundried Tomato, Pepperoni, Chorizo Sausage, Kalamata Olives, Fire Roasted Peppers Then Topped With Shaved Parmesan Cheese On A Spicy Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Garlic", "Sundried Tomato", "Pepperoni", "Chorizo Sausage", "Kalamata Olives", "Fire Roasted Peppers", "Shaved Parmesan Cheese", "Spicy Tomato Base"] },
                { "name": "The Godfather", "description": "Mozzarella Cheese, Garlic, Onion, Capsicum, Fresh Mushroom Topped With Diced Bacon & Chorizo Sausage On A Spicy Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Garlic", "Onion", "Capsicum", "Fresh Mushroom", "Diced Bacon", "Chorizo Sausage", "Spicy Tomato Base"] },
                { "name": "The Mona Lisa", "description": "Mozzarella Cheese, Garlic, Sundried Tomatoes, Pepperoni, Fresh Mushroom, Fire Roasted Peppers, Roasted Chicken, Kalamata Olives On A spicy Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Garlic", "Sundried Tomatoes", "Pepperoni", "Fresh Mushroom", "Fire Roasted Peppers", "Roasted Chicken", "Kalamata Olives", "Spicy Tomato Base"] },
                { "name": "Creamy Prawn Delight", "description": "Mozzarella Cheese, Onion, Fresh Tomato, King Prawns On A Creamy Lemon Sauce Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Onion", "Fresh Tomato", "King Prawns", "Creamy Lemon Sauce Base"] },
                { "name": "Seafood", "description": "Mozzarella Cheese, Garlic, Prawns, Mussels On A Tomato Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 16.50, "Large": 21.50, "Family": 28.50, "Party": 36.50 }, "ingredients": ["Mozzarella Cheese", "Garlic", "Prawns", "Mussels", "Tomato Base"] },
                { "name": "Vegetarian Delight", "description": "Mozzarella Cheese, Fire Roasted Peppers, Onion, Feta Cheese, Oven Roasted Pumpkin, Kalamata Olives Topped With A Swirl Of Mint Yoghurt On A Basil Pesto Base", "sizes": ["Regular", "Large", "Family", "Party"], "prices": { "Regular": 18.50, "Large": 23.50, "Family": 30.50, "Party": 38.50 }, "ingredients": ["Mozzarella Cheese", "Fire Roasted Peppers", "Onion", "Feta Cheese", "Oven Roasted Pumpkin", "Kalamata Olives", "Mint Yoghurt", "Basil Pesto Base"] }
            ]
        },
        {
            "name": "Drinks",
            "items": [
                { "name": "Coke (375ml)", "description": "", "prices": { "Default": 3.50 } },
                { "name": "Coke Zero (375ml)", "description": "", "prices": { "Default": 3.50 } },
                { "name": "Pepsi (1.25L)", "description": "", "prices": { "Default": 6.00 } },
                { "name": "Pepsi Max (1.25L)", "description": "", "prices": { "Default": 6.00 } },
                { "name": "Sunkist (1.25L)", "description": "", "prices": { "Default": 6.00 } },
                { "name": "7UP (1.25L)", "description": "", "prices": { "Default": 6.00 } },
                { "name": "Solo (1.25L)", "description": "", "prices": { "Default": 6.00 } },
                { "name": "Water (600ml)", "description": "", "prices": { "Default": 2.90 } },
                { "name": "Coke (2L)", "description": "", "prices": { "Default": 7.60 } },
                { "name": "Apple Juice (250ml)", "description": "", "prices": { "Default": 2.80 } },
                { "name": "Orange Juice (250ml)", "description": "", "prices": { "Default": 2.80 } },
                { "name": "Tropical Juice (250ml)", "description": "", "prices": { "Default": 2.80 } },
                { "name": "Lipton Peach Ice Tea", "description": "", "prices": { "Default": 4.50 } }
            ]
        },
        {
            "name": "Mini Pizza",
            "items": [
                { "name": "MINI Cheese", "description": "Tomato Sauce & Cheese", "prices": { "Default": 9.90 } },
                { "name": "MINI Margherita", "description": "Garlic, Oregano, Mozzarella Cheese, Fresh Tomato On A Tomato Base.", "prices": { "Default": 9.90 } },
                { "name": "MINI Australian", "description": "Double Mozzarella Cheese, Ham On A Tomato Base", "prices": { "Default": 9.90 } },
                { "name": "MINI Ham & Pineapple", "description": "Mozzarella Cheese, Ham, Pineapple On a Tomato Base", "prices": { "Default": 9.90 } },
                { "name": "MINI Meatlovers", "description": "Mozzarella Cheese, Ham, Salami, Bacon On A Tomato Base", "prices": { "Default": 9.90 } },
                { "name": "MINI Chicken & Pineapple", "description": "Mozzarella Cheese, Pineapple, Roasted Chicken on a Tomato Base", "prices": { "Default": 9.90 } },
                { "name": "MINI Double Burger Bite", "description": "Mozzarella Cheese, Bacon, Ground Beef Topped With A Swirl Of Aioli On A BBQ Sauce Base", "prices": { "Default": 9.90 } },
                { "name": "MINI Vegetarian", "description": "Mozzarella Cheese, Onion, Capsicum, Fresh Mushroom & Pineapple On A Tomato Base", "prices": { "Default": 9.90 } }
            ]
        },
        {
            "name": "Special",
            "items": [
                { "name": "Dessert combo meal", "description": "2 Large Pizzas, Garlic Bread, 1.25L Soft Drink & Tiramisu/Pancake/Chocolate Mousse/Banoffee Pie", "prices": { "Default": 57.50 } },
                { "name": "Dinner for two", "description": "2 x Regular Pizza, 1 Garlic Bread, 1 1.25L Drink", "prices": { "Default": 34.50 } },
                { "name": "Double trouble", "description": "2 x Large Pizzas, 1 x Garlic Bread, 1 x 1.25L Drink", "prices": { "Default": 46.50 } },
                { "name": "Tripple meal deal", "description": "3 x Large Pizzas, 1 x Garlic Bread, 1 x 1.25L Drink", "prices": { "Default": 62.50 } },
                { "name": "Family meal deal", "description": "2 x Family Pizzas, 1 x Garlic Bread, 1 x 1.25L Drink", "prices": { "Default": 54.50 } },
                { "name": "Party meal deal", "description": "2 x Party Pizzas, 2 x Garlic Bread, 2 x 1.25L Drink", "prices": { "Default": 79.50 } },
                { "name": "Pick a box lasagne", "description": "2 x Large Pizzas, 1 x Garlic Bread, Lasagna", "prices": { "Default": 53.90 } },
                { "name": "Pick a box potato skins", "description": "2 x Large Pizzas, 1 x Garlic Bread, 1 X Potato Skins", "prices": { "Default": 55.90 } },
                { "name": "Pick a box chicken wingettes", "description": "2 x Large Pizzas, 1 x Garlic Bread, 12 BBQ Wngettes", "prices": { "Default": 53.90 } },
                { "name": "Pick a box wedges", "description": "2 x Large Pizzas, 1 x Garlic Bread, Wedges", "prices": { "Default": 53.90 } },
                { "name": "Kids meal deal", "description": "Any Mini Pizza, 5 Chicken Nuggets & A Small Juice", "prices": { "Default": 14.50 } },
                { "name": "Just for one", "description": "Large Pizza, 1 Garlic Bread & 1 X 1.25L Soft Drink", "prices": { "Default": 27.90 } },
                { "name": "Calzone meal deal", "description": "Any 2 Calzones, 1 Garlic Bread & 1.25L Soft Drink", "prices": { "Default": 52.90 } },
                { "name": "Pizza and calzone meal deal", "description": "1x Large Pizza, 1x Calzone, 1x Garlic Bread & 1x 1.25L Soft Drink", "prices": { "Default": 52.90 } }
            ]
        }
    ]
};
export const extrasData = { "Popular": [ { "name": "fresh basil", "price": 0.50 }, { "name": "mint yoghurt", "price": 1.00 } ], "Cheese": [ { "name": "feta cheese", "price": 1.00 }, { "name": "mozzarella cheese", "price": 1.00 } ], "Meat": [ { "name": "bacon", "price": 1.00 }, { "name": "chicken", "price": 2.00 } ], "Veggies": [ { "name": "capsicum", "price": 1.00 }, { "name": "onion", "price": 1.00 } ], "Sauce": [ { "name": "aioli", "price": 1.00 }, { "name": "bbq sauce", "price": 0.00 } ] };
